{
  'language': 'node_js',
  'os': ['linux'],
  'dist': 'xenial',
  'node_js': ['14.15.1'],
  'install': ['npm ci'],
  'script': ['npm run docs:build'],
  'deploy':
    [
      {
        'provider': 'pages',
        'strategy': 'git',
        'skip_cleanup': true,
        'local_dir': 'docs/.vuepress/dist',
        'keep_history': true,
        'on': { 'branch': ['master'] },
        'token': '$GITHUB_TOKEN',
      },
    ],
}
# language: node_js
# node_js:
#   - 14.15.1
# install:
#   - npm ci # npm ci
# script:
#   - npm run docs:build # npm run docs:build
# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: docs/.vuepress/dist
#   github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
#   keep_history: true
#   on:
#     branch: master
